name: Update Badges

on:
  schedule:
    - cron: '0 18 * * *'  # 1 AM Thailand time (UTC+7)
  workflow_dispatch: # Allow manual runs

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: ${{ github.actor }} # Uses your GitHub username
          NUMBER_LAST_BADGES: 0 # Show last 10 badges (0 = all)
